# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import json
import pulumi
import pulumi.runtime
from .. import utilities, tables

class ApnsVoipSandboxChannel(pulumi.CustomResource):
    application_id: pulumi.Output[str]
    bundle_id: pulumi.Output[str]
    certificate: pulumi.Output[str]
    default_authentication_method: pulumi.Output[str]
    enabled: pulumi.Output[bool]
    private_key: pulumi.Output[str]
    team_id: pulumi.Output[str]
    token_key: pulumi.Output[str]
    token_key_id: pulumi.Output[str]
    def __init__(__self__, __name__, __opts__=None, application_id=None, bundle_id=None, certificate=None, default_authentication_method=None, enabled=None, private_key=None, team_id=None, token_key=None, token_key_id=None):
        """
        ## ---
        
        layout: "aws"
        page_title: "AWS: aws_pinpoint_apns_voip_sandbox_channel"
        sidebar_current: "docs-aws-resource-pinpoint-apns-voip-sandbox-channel"
        description: |-
          Provides a Pinpoint APNs VoIP Sandbox Channel resource.
        ---
        
        # aws_pinpoint_apns_voip_sandbox_channel
        
        Provides a Pinpoint APNs VoIP Sandbox Channel resource.
        
        > **Note:** All arguments, including certificates and tokens, will be stored in the raw state as plain-text.
        [Read more about sensitive data in state](https://www.terraform.io/docs/state/sensitive-data.html).
        
        ## Argument Reference
        
        The following arguments are supported:
        
        * `application_id` - (Required) The application ID.
        * `enabled` - (Optional) Whether the channel is enabled or disabled. Defaults to `true`.
        * `default_authentication_method` - (Optional) The default authentication method used for APNs. 
          __NOTE__: Amazon Pinpoint uses this default for every APNs push notification that you send using the console.
          You can override the default when you send a message programmatically using the Amazon Pinpoint API, the AWS CLI, or an AWS SDK.
          If your default authentication type fails, Amazon Pinpoint doesn't attempt to use the other authentication type.
        
        One of the following sets of credentials is also required.
        
        If you choose to use __Certificate credentials__ you will have to provide:
        * `certificate` - (Required) The pem encoded TLS Certificate from Apple.
        * `private_key` - (Required) The Certificate Private Key file (ie. `.key` file).
        
        If you choose to use __Key credentials__ you will have to provide:
        * `bundle_id` - (Required) The ID assigned to your iOS app. To find this value, choose Certificates, IDs & Profiles, choose App IDs in the Identifiers section, and choose your app.
        * `team_id` - (Required) The ID assigned to your Apple developer account team. This value is provided on the Membership page.
        * `token_key` - (Required) The `.p8` file that you download from your Apple developer account when you create an authentication key. 
        * `token_key_id` - (Required) The ID assigned to your signing key. To find this value, choose Certificates, IDs & Profiles, and choose your key in the Keys section.
        
        :param str __name__: The name of the resource.
        :param pulumi.ResourceOptions __opts__: Options for the resource.
        :param pulumi.Input[str] application_id
        :param pulumi.Input[str] bundle_id
        :param pulumi.Input[str] certificate
        :param pulumi.Input[str] default_authentication_method
        :param pulumi.Input[bool] enabled
        :param pulumi.Input[str] private_key
        :param pulumi.Input[str] team_id
        :param pulumi.Input[str] token_key
        :param pulumi.Input[str] token_key_id
        """
        if not __name__:
            raise TypeError('Missing resource name argument (for URN creation)')
        if not isinstance(__name__, str):
            raise TypeError('Expected resource name to be a string')
        if __opts__ and not isinstance(__opts__, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')

        __props__ = dict()

        if not application_id:
            raise TypeError('Missing required property application_id')
        __props__['application_id'] = application_id

        __props__['bundle_id'] = bundle_id

        __props__['certificate'] = certificate

        __props__['default_authentication_method'] = default_authentication_method

        __props__['enabled'] = enabled

        __props__['private_key'] = private_key

        __props__['team_id'] = team_id

        __props__['token_key'] = token_key

        __props__['token_key_id'] = token_key_id

        super(ApnsVoipSandboxChannel, __self__).__init__(
            'aws:pinpoint/apnsVoipSandboxChannel:ApnsVoipSandboxChannel',
            __name__,
            __props__,
            __opts__)


    def translate_output_property(self, prop):
        return tables._CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop

    def translate_input_property(self, prop):
        return tables._SNAKE_TO_CAMEL_CASE_TABLE.get(prop) or prop

