// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package getAmiFilter

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type GetAmiFilter struct {
	// The name of the AMI that was provided during image creation.
	Name string `pulumi:"name"`
	Values []string `pulumi:"values"`
}

type GetAmiFilterInput interface {
	pulumi.Input

	ToGetAmiFilterOutput() GetAmiFilterOutput
	ToGetAmiFilterOutputWithContext(context.Context) GetAmiFilterOutput
}

type GetAmiFilterArgs struct {
	// The name of the AMI that was provided during image creation.
	Name pulumi.StringInput `pulumi:"name"`
	Values pulumi.StringArrayInput `pulumi:"values"`
}

func (GetAmiFilterArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAmiFilter)(nil)).Elem()
}

func (i GetAmiFilterArgs) ToGetAmiFilterOutput() GetAmiFilterOutput {
	return i.ToGetAmiFilterOutputWithContext(context.Background())
}

func (i GetAmiFilterArgs) ToGetAmiFilterOutputWithContext(ctx context.Context) GetAmiFilterOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetAmiFilterOutput)
}

type GetAmiFilterArrayInput interface {
	pulumi.Input

	ToGetAmiFilterArrayOutput() GetAmiFilterArrayOutput
	ToGetAmiFilterArrayOutputWithContext(context.Context) GetAmiFilterArrayOutput
}

type GetAmiFilterArray []GetAmiFilterInput

func (GetAmiFilterArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetAmiFilter)(nil)).Elem()
}

func (i GetAmiFilterArray) ToGetAmiFilterArrayOutput() GetAmiFilterArrayOutput {
	return i.ToGetAmiFilterArrayOutputWithContext(context.Background())
}

func (i GetAmiFilterArray) ToGetAmiFilterArrayOutputWithContext(ctx context.Context) GetAmiFilterArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetAmiFilterArrayOutput)
}

type GetAmiFilterOutput struct { *pulumi.OutputState }

func (GetAmiFilterOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAmiFilter)(nil)).Elem()
}

func (o GetAmiFilterOutput) ToGetAmiFilterOutput() GetAmiFilterOutput {
	return o
}

func (o GetAmiFilterOutput) ToGetAmiFilterOutputWithContext(ctx context.Context) GetAmiFilterOutput {
	return o
}

// The name of the AMI that was provided during image creation.
func (o GetAmiFilterOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func (v GetAmiFilter) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetAmiFilterOutput) Values() pulumi.StringArrayOutput {
	return o.ApplyT(func (v GetAmiFilter) []string { return v.Values }).(pulumi.StringArrayOutput)
}

type GetAmiFilterArrayOutput struct { *pulumi.OutputState}

func (GetAmiFilterArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetAmiFilter)(nil)).Elem()
}

func (o GetAmiFilterArrayOutput) ToGetAmiFilterArrayOutput() GetAmiFilterArrayOutput {
	return o
}

func (o GetAmiFilterArrayOutput) ToGetAmiFilterArrayOutputWithContext(ctx context.Context) GetAmiFilterArrayOutput {
	return o
}

func (o GetAmiFilterArrayOutput) Index(i pulumi.IntInput) GetAmiFilterOutput {
	return pulumi.All(o, i).ApplyT(func (vs []interface{}) GetAmiFilter {
		return vs[0].([]GetAmiFilter)[vs[1].(int)]
	}).(GetAmiFilterOutput)
}

func init() {
	pulumi.RegisterOutputType(GetAmiFilterOutput{})
	pulumi.RegisterOutputType(GetAmiFilterArrayOutput{})
}
