// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package directconnect

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type PrivateVirtualInterface struct {
	pulumi.CustomResourceState

	AddressFamily     pulumi.StringOutput    `pulumi:"addressFamily"`
	AmazonAddress     pulumi.StringOutput    `pulumi:"amazonAddress"`
	AmazonSideAsn     pulumi.StringOutput    `pulumi:"amazonSideAsn"`
	Arn               pulumi.StringOutput    `pulumi:"arn"`
	AwsDevice         pulumi.StringOutput    `pulumi:"awsDevice"`
	BgpAsn            pulumi.IntOutput       `pulumi:"bgpAsn"`
	BgpAuthKey        pulumi.StringOutput    `pulumi:"bgpAuthKey"`
	ConnectionId      pulumi.StringOutput    `pulumi:"connectionId"`
	CustomerAddress   pulumi.StringOutput    `pulumi:"customerAddress"`
	DxGatewayId       pulumi.StringPtrOutput `pulumi:"dxGatewayId"`
	JumboFrameCapable pulumi.BoolOutput      `pulumi:"jumboFrameCapable"`
	Mtu               pulumi.IntPtrOutput    `pulumi:"mtu"`
	Name              pulumi.StringOutput    `pulumi:"name"`
	Tags              pulumi.StringMapOutput `pulumi:"tags"`
	Vlan              pulumi.IntOutput       `pulumi:"vlan"`
	VpnGatewayId      pulumi.StringPtrOutput `pulumi:"vpnGatewayId"`
}

// NewPrivateVirtualInterface registers a new resource with the given unique name, arguments, and options.
func NewPrivateVirtualInterface(ctx *pulumi.Context,
	name string, args *PrivateVirtualInterfaceArgs, opts ...pulumi.ResourceOption) (*PrivateVirtualInterface, error) {
	if args == nil || args.AddressFamily == nil {
		return nil, errors.New("missing required argument 'AddressFamily'")
	}
	if args == nil || args.BgpAsn == nil {
		return nil, errors.New("missing required argument 'BgpAsn'")
	}
	if args == nil || args.ConnectionId == nil {
		return nil, errors.New("missing required argument 'ConnectionId'")
	}
	if args == nil || args.Vlan == nil {
		return nil, errors.New("missing required argument 'Vlan'")
	}
	if args == nil {
		args = &PrivateVirtualInterfaceArgs{}
	}
	var resource PrivateVirtualInterface
	err := ctx.RegisterResource("aws:directconnect/privateVirtualInterface:PrivateVirtualInterface", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPrivateVirtualInterface gets an existing PrivateVirtualInterface resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPrivateVirtualInterface(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PrivateVirtualInterfaceState, opts ...pulumi.ResourceOption) (*PrivateVirtualInterface, error) {
	var resource PrivateVirtualInterface
	err := ctx.ReadResource("aws:directconnect/privateVirtualInterface:PrivateVirtualInterface", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PrivateVirtualInterface resources.
type privateVirtualInterfaceState struct {
	AddressFamily     *string           `pulumi:"addressFamily"`
	AmazonAddress     *string           `pulumi:"amazonAddress"`
	AmazonSideAsn     *string           `pulumi:"amazonSideAsn"`
	Arn               *string           `pulumi:"arn"`
	AwsDevice         *string           `pulumi:"awsDevice"`
	BgpAsn            *int              `pulumi:"bgpAsn"`
	BgpAuthKey        *string           `pulumi:"bgpAuthKey"`
	ConnectionId      *string           `pulumi:"connectionId"`
	CustomerAddress   *string           `pulumi:"customerAddress"`
	DxGatewayId       *string           `pulumi:"dxGatewayId"`
	JumboFrameCapable *bool             `pulumi:"jumboFrameCapable"`
	Mtu               *int              `pulumi:"mtu"`
	Name              *string           `pulumi:"name"`
	Tags              map[string]string `pulumi:"tags"`
	Vlan              *int              `pulumi:"vlan"`
	VpnGatewayId      *string           `pulumi:"vpnGatewayId"`
}

type PrivateVirtualInterfaceState struct {
	AddressFamily     pulumi.StringPtrInput
	AmazonAddress     pulumi.StringPtrInput
	AmazonSideAsn     pulumi.StringPtrInput
	Arn               pulumi.StringPtrInput
	AwsDevice         pulumi.StringPtrInput
	BgpAsn            pulumi.IntPtrInput
	BgpAuthKey        pulumi.StringPtrInput
	ConnectionId      pulumi.StringPtrInput
	CustomerAddress   pulumi.StringPtrInput
	DxGatewayId       pulumi.StringPtrInput
	JumboFrameCapable pulumi.BoolPtrInput
	Mtu               pulumi.IntPtrInput
	Name              pulumi.StringPtrInput
	Tags              pulumi.StringMapInput
	Vlan              pulumi.IntPtrInput
	VpnGatewayId      pulumi.StringPtrInput
}

func (PrivateVirtualInterfaceState) ElementType() reflect.Type {
	return reflect.TypeOf((*privateVirtualInterfaceState)(nil)).Elem()
}

type privateVirtualInterfaceArgs struct {
	AddressFamily   string            `pulumi:"addressFamily"`
	AmazonAddress   *string           `pulumi:"amazonAddress"`
	BgpAsn          int               `pulumi:"bgpAsn"`
	BgpAuthKey      *string           `pulumi:"bgpAuthKey"`
	ConnectionId    string            `pulumi:"connectionId"`
	CustomerAddress *string           `pulumi:"customerAddress"`
	DxGatewayId     *string           `pulumi:"dxGatewayId"`
	Mtu             *int              `pulumi:"mtu"`
	Name            *string           `pulumi:"name"`
	Tags            map[string]string `pulumi:"tags"`
	Vlan            int               `pulumi:"vlan"`
	VpnGatewayId    *string           `pulumi:"vpnGatewayId"`
}

// The set of arguments for constructing a PrivateVirtualInterface resource.
type PrivateVirtualInterfaceArgs struct {
	AddressFamily   pulumi.StringInput
	AmazonAddress   pulumi.StringPtrInput
	BgpAsn          pulumi.IntInput
	BgpAuthKey      pulumi.StringPtrInput
	ConnectionId    pulumi.StringInput
	CustomerAddress pulumi.StringPtrInput
	DxGatewayId     pulumi.StringPtrInput
	Mtu             pulumi.IntPtrInput
	Name            pulumi.StringPtrInput
	Tags            pulumi.StringMapInput
	Vlan            pulumi.IntInput
	VpnGatewayId    pulumi.StringPtrInput
}

func (PrivateVirtualInterfaceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*privateVirtualInterfaceArgs)(nil)).Elem()
}
