// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package elasticsearch

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupDomain(ctx *pulumi.Context, args *LookupDomainArgs, opts ...pulumi.InvokeOption) (*LookupDomainResult, error) {
	var rv LookupDomainResult
	err := ctx.Invoke("aws:elasticsearch/getDomain:getDomain", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDomain.
type LookupDomainArgs struct {
	DomainName string            `pulumi:"domainName"`
	Tags       map[string]string `pulumi:"tags"`
}

// A collection of values returned by getDomain.
type LookupDomainResult struct {
	AccessPolicies          string                            `pulumi:"accessPolicies"`
	AdvancedOptions         map[string]string                 `pulumi:"advancedOptions"`
	AdvancedSecurityOptions []GetDomainAdvancedSecurityOption `pulumi:"advancedSecurityOptions"`
	Arn                     string                            `pulumi:"arn"`
	ClusterConfigs          []GetDomainClusterConfig          `pulumi:"clusterConfigs"`
	CognitoOptions          []GetDomainCognitoOption          `pulumi:"cognitoOptions"`
	Created                 bool                              `pulumi:"created"`
	Deleted                 bool                              `pulumi:"deleted"`
	DomainId                string                            `pulumi:"domainId"`
	DomainName              string                            `pulumi:"domainName"`
	EbsOptions              []GetDomainEbsOption              `pulumi:"ebsOptions"`
	ElasticsearchVersion    string                            `pulumi:"elasticsearchVersion"`
	EncryptionAtRests       []GetDomainEncryptionAtRest       `pulumi:"encryptionAtRests"`
	Endpoint                string                            `pulumi:"endpoint"`
	// The provider-assigned unique ID for this managed resource.
	Id                    string                          `pulumi:"id"`
	KibanaEndpoint        string                          `pulumi:"kibanaEndpoint"`
	LogPublishingOptions  []GetDomainLogPublishingOption  `pulumi:"logPublishingOptions"`
	NodeToNodeEncryptions []GetDomainNodeToNodeEncryption `pulumi:"nodeToNodeEncryptions"`
	Processing            bool                            `pulumi:"processing"`
	SnapshotOptions       []GetDomainSnapshotOption       `pulumi:"snapshotOptions"`
	Tags                  map[string]string               `pulumi:"tags"`
	VpcOptions            []GetDomainVpcOption            `pulumi:"vpcOptions"`
}
