// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package NodeGroupResourceAutoscalingGroup

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type NodeGroupResourceAutoscalingGroup struct {
	// Name of the AutoScaling Group.
	Name *string `pulumi:"name"`
}

type NodeGroupResourceAutoscalingGroupInput interface {
	pulumi.Input

	ToNodeGroupResourceAutoscalingGroupOutput() NodeGroupResourceAutoscalingGroupOutput
	ToNodeGroupResourceAutoscalingGroupOutputWithContext(context.Context) NodeGroupResourceAutoscalingGroupOutput
}

type NodeGroupResourceAutoscalingGroupArgs struct {
	// Name of the AutoScaling Group.
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (NodeGroupResourceAutoscalingGroupArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*NodeGroupResourceAutoscalingGroup)(nil)).Elem()
}

func (i NodeGroupResourceAutoscalingGroupArgs) ToNodeGroupResourceAutoscalingGroupOutput() NodeGroupResourceAutoscalingGroupOutput {
	return i.ToNodeGroupResourceAutoscalingGroupOutputWithContext(context.Background())
}

func (i NodeGroupResourceAutoscalingGroupArgs) ToNodeGroupResourceAutoscalingGroupOutputWithContext(ctx context.Context) NodeGroupResourceAutoscalingGroupOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NodeGroupResourceAutoscalingGroupOutput)
}

type NodeGroupResourceAutoscalingGroupArrayInput interface {
	pulumi.Input

	ToNodeGroupResourceAutoscalingGroupArrayOutput() NodeGroupResourceAutoscalingGroupArrayOutput
	ToNodeGroupResourceAutoscalingGroupArrayOutputWithContext(context.Context) NodeGroupResourceAutoscalingGroupArrayOutput
}

type NodeGroupResourceAutoscalingGroupArray []NodeGroupResourceAutoscalingGroupInput

func (NodeGroupResourceAutoscalingGroupArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]NodeGroupResourceAutoscalingGroup)(nil)).Elem()
}

func (i NodeGroupResourceAutoscalingGroupArray) ToNodeGroupResourceAutoscalingGroupArrayOutput() NodeGroupResourceAutoscalingGroupArrayOutput {
	return i.ToNodeGroupResourceAutoscalingGroupArrayOutputWithContext(context.Background())
}

func (i NodeGroupResourceAutoscalingGroupArray) ToNodeGroupResourceAutoscalingGroupArrayOutputWithContext(ctx context.Context) NodeGroupResourceAutoscalingGroupArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NodeGroupResourceAutoscalingGroupArrayOutput)
}

type NodeGroupResourceAutoscalingGroupOutput struct { *pulumi.OutputState }

func (NodeGroupResourceAutoscalingGroupOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*NodeGroupResourceAutoscalingGroup)(nil)).Elem()
}

func (o NodeGroupResourceAutoscalingGroupOutput) ToNodeGroupResourceAutoscalingGroupOutput() NodeGroupResourceAutoscalingGroupOutput {
	return o
}

func (o NodeGroupResourceAutoscalingGroupOutput) ToNodeGroupResourceAutoscalingGroupOutputWithContext(ctx context.Context) NodeGroupResourceAutoscalingGroupOutput {
	return o
}

// Name of the AutoScaling Group.
func (o NodeGroupResourceAutoscalingGroupOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func (v NodeGroupResourceAutoscalingGroup) *string { return v.Name }).(pulumi.StringPtrOutput)
}

type NodeGroupResourceAutoscalingGroupArrayOutput struct { *pulumi.OutputState}

func (NodeGroupResourceAutoscalingGroupArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]NodeGroupResourceAutoscalingGroup)(nil)).Elem()
}

func (o NodeGroupResourceAutoscalingGroupArrayOutput) ToNodeGroupResourceAutoscalingGroupArrayOutput() NodeGroupResourceAutoscalingGroupArrayOutput {
	return o
}

func (o NodeGroupResourceAutoscalingGroupArrayOutput) ToNodeGroupResourceAutoscalingGroupArrayOutputWithContext(ctx context.Context) NodeGroupResourceAutoscalingGroupArrayOutput {
	return o
}

func (o NodeGroupResourceAutoscalingGroupArrayOutput) Index(i pulumi.IntInput) NodeGroupResourceAutoscalingGroupOutput {
	return pulumi.All(o, i).ApplyT(func (vs []interface{}) NodeGroupResourceAutoscalingGroup {
		return vs[0].([]NodeGroupResourceAutoscalingGroup)[vs[1].(int)]
	}).(NodeGroupResourceAutoscalingGroupOutput)
}

func init() {
	pulumi.RegisterOutputType(NodeGroupResourceAutoscalingGroupOutput{})
	pulumi.RegisterOutputType(NodeGroupResourceAutoscalingGroupArrayOutput{})
}
