// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package AnalyticsApplicationInputsParallelism

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type AnalyticsApplicationInputsParallelism struct {
	Count int `pulumi:"count"`
}

type AnalyticsApplicationInputsParallelismInput interface {
	pulumi.Input

	ToAnalyticsApplicationInputsParallelismOutput() AnalyticsApplicationInputsParallelismOutput
	ToAnalyticsApplicationInputsParallelismOutputWithContext(context.Context) AnalyticsApplicationInputsParallelismOutput
}

type AnalyticsApplicationInputsParallelismArgs struct {
	Count pulumi.IntInput `pulumi:"count"`
}

func (AnalyticsApplicationInputsParallelismArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AnalyticsApplicationInputsParallelism)(nil)).Elem()
}

func (i AnalyticsApplicationInputsParallelismArgs) ToAnalyticsApplicationInputsParallelismOutput() AnalyticsApplicationInputsParallelismOutput {
	return i.ToAnalyticsApplicationInputsParallelismOutputWithContext(context.Background())
}

func (i AnalyticsApplicationInputsParallelismArgs) ToAnalyticsApplicationInputsParallelismOutputWithContext(ctx context.Context) AnalyticsApplicationInputsParallelismOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AnalyticsApplicationInputsParallelismOutput)
}

func (i AnalyticsApplicationInputsParallelismArgs) ToAnalyticsApplicationInputsParallelismPtrOutput() AnalyticsApplicationInputsParallelismPtrOutput {
	return i.ToAnalyticsApplicationInputsParallelismPtrOutputWithContext(context.Background())
}

func (i AnalyticsApplicationInputsParallelismArgs) ToAnalyticsApplicationInputsParallelismPtrOutputWithContext(ctx context.Context) AnalyticsApplicationInputsParallelismPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AnalyticsApplicationInputsParallelismOutput).ToAnalyticsApplicationInputsParallelismPtrOutputWithContext(ctx)
}

type AnalyticsApplicationInputsParallelismPtrInput interface {
	pulumi.Input

	ToAnalyticsApplicationInputsParallelismPtrOutput() AnalyticsApplicationInputsParallelismPtrOutput
	ToAnalyticsApplicationInputsParallelismPtrOutputWithContext(context.Context) AnalyticsApplicationInputsParallelismPtrOutput
}

type analyticsApplicationInputsParallelismPtrType AnalyticsApplicationInputsParallelismArgs

func AnalyticsApplicationInputsParallelismPtr(v *AnalyticsApplicationInputsParallelismArgs) AnalyticsApplicationInputsParallelismPtrInput {	return (*analyticsApplicationInputsParallelismPtrType)(v)
}

func (*analyticsApplicationInputsParallelismPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**AnalyticsApplicationInputsParallelism)(nil)).Elem()
}

func (i *analyticsApplicationInputsParallelismPtrType) ToAnalyticsApplicationInputsParallelismPtrOutput() AnalyticsApplicationInputsParallelismPtrOutput {
	return i.ToAnalyticsApplicationInputsParallelismPtrOutputWithContext(context.Background())
}

func (i *analyticsApplicationInputsParallelismPtrType) ToAnalyticsApplicationInputsParallelismPtrOutputWithContext(ctx context.Context) AnalyticsApplicationInputsParallelismPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AnalyticsApplicationInputsParallelismPtrOutput)
}

type AnalyticsApplicationInputsParallelismOutput struct { *pulumi.OutputState }

func (AnalyticsApplicationInputsParallelismOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AnalyticsApplicationInputsParallelism)(nil)).Elem()
}

func (o AnalyticsApplicationInputsParallelismOutput) ToAnalyticsApplicationInputsParallelismOutput() AnalyticsApplicationInputsParallelismOutput {
	return o
}

func (o AnalyticsApplicationInputsParallelismOutput) ToAnalyticsApplicationInputsParallelismOutputWithContext(ctx context.Context) AnalyticsApplicationInputsParallelismOutput {
	return o
}

func (o AnalyticsApplicationInputsParallelismOutput) ToAnalyticsApplicationInputsParallelismPtrOutput() AnalyticsApplicationInputsParallelismPtrOutput {
	return o.ToAnalyticsApplicationInputsParallelismPtrOutputWithContext(context.Background())
}

func (o AnalyticsApplicationInputsParallelismOutput) ToAnalyticsApplicationInputsParallelismPtrOutputWithContext(ctx context.Context) AnalyticsApplicationInputsParallelismPtrOutput {
	return o.ApplyT(func(v AnalyticsApplicationInputsParallelism) *AnalyticsApplicationInputsParallelism {
		return &v
	}).(AnalyticsApplicationInputsParallelismPtrOutput)
}
func (o AnalyticsApplicationInputsParallelismOutput) Count() pulumi.IntOutput {
	return o.ApplyT(func (v AnalyticsApplicationInputsParallelism) int { return v.Count }).(pulumi.IntOutput)
}

type AnalyticsApplicationInputsParallelismPtrOutput struct { *pulumi.OutputState}

func (AnalyticsApplicationInputsParallelismPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AnalyticsApplicationInputsParallelism)(nil)).Elem()
}

func (o AnalyticsApplicationInputsParallelismPtrOutput) ToAnalyticsApplicationInputsParallelismPtrOutput() AnalyticsApplicationInputsParallelismPtrOutput {
	return o
}

func (o AnalyticsApplicationInputsParallelismPtrOutput) ToAnalyticsApplicationInputsParallelismPtrOutputWithContext(ctx context.Context) AnalyticsApplicationInputsParallelismPtrOutput {
	return o
}

func (o AnalyticsApplicationInputsParallelismPtrOutput) Elem() AnalyticsApplicationInputsParallelismOutput {
	return o.ApplyT(func (v *AnalyticsApplicationInputsParallelism) AnalyticsApplicationInputsParallelism { return *v }).(AnalyticsApplicationInputsParallelismOutput)
}

func (o AnalyticsApplicationInputsParallelismPtrOutput) Count() pulumi.IntOutput {
	return o.ApplyT(func (v AnalyticsApplicationInputsParallelism) int { return v.Count }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(AnalyticsApplicationInputsParallelismOutput{})
	pulumi.RegisterOutputType(AnalyticsApplicationInputsParallelismPtrOutput{})
}
