// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package AmiEphemeralBlockDevice

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type AmiEphemeralBlockDevice struct {
	DeviceName string `pulumi:"deviceName"`
	VirtualName string `pulumi:"virtualName"`
}

type AmiEphemeralBlockDeviceInput interface {
	pulumi.Input

	ToAmiEphemeralBlockDeviceOutput() AmiEphemeralBlockDeviceOutput
	ToAmiEphemeralBlockDeviceOutputWithContext(context.Context) AmiEphemeralBlockDeviceOutput
}

type AmiEphemeralBlockDeviceArgs struct {
	DeviceName pulumi.StringInput `pulumi:"deviceName"`
	VirtualName pulumi.StringInput `pulumi:"virtualName"`
}

func (AmiEphemeralBlockDeviceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AmiEphemeralBlockDevice)(nil)).Elem()
}

func (i AmiEphemeralBlockDeviceArgs) ToAmiEphemeralBlockDeviceOutput() AmiEphemeralBlockDeviceOutput {
	return i.ToAmiEphemeralBlockDeviceOutputWithContext(context.Background())
}

func (i AmiEphemeralBlockDeviceArgs) ToAmiEphemeralBlockDeviceOutputWithContext(ctx context.Context) AmiEphemeralBlockDeviceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AmiEphemeralBlockDeviceOutput)
}

type AmiEphemeralBlockDeviceArrayInput interface {
	pulumi.Input

	ToAmiEphemeralBlockDeviceArrayOutput() AmiEphemeralBlockDeviceArrayOutput
	ToAmiEphemeralBlockDeviceArrayOutputWithContext(context.Context) AmiEphemeralBlockDeviceArrayOutput
}

type AmiEphemeralBlockDeviceArray []AmiEphemeralBlockDeviceInput

func (AmiEphemeralBlockDeviceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]AmiEphemeralBlockDevice)(nil)).Elem()
}

func (i AmiEphemeralBlockDeviceArray) ToAmiEphemeralBlockDeviceArrayOutput() AmiEphemeralBlockDeviceArrayOutput {
	return i.ToAmiEphemeralBlockDeviceArrayOutputWithContext(context.Background())
}

func (i AmiEphemeralBlockDeviceArray) ToAmiEphemeralBlockDeviceArrayOutputWithContext(ctx context.Context) AmiEphemeralBlockDeviceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AmiEphemeralBlockDeviceArrayOutput)
}

type AmiEphemeralBlockDeviceOutput struct { *pulumi.OutputState }

func (AmiEphemeralBlockDeviceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AmiEphemeralBlockDevice)(nil)).Elem()
}

func (o AmiEphemeralBlockDeviceOutput) ToAmiEphemeralBlockDeviceOutput() AmiEphemeralBlockDeviceOutput {
	return o
}

func (o AmiEphemeralBlockDeviceOutput) ToAmiEphemeralBlockDeviceOutputWithContext(ctx context.Context) AmiEphemeralBlockDeviceOutput {
	return o
}

func (o AmiEphemeralBlockDeviceOutput) DeviceName() pulumi.StringOutput {
	return o.ApplyT(func (v AmiEphemeralBlockDevice) string { return v.DeviceName }).(pulumi.StringOutput)
}

func (o AmiEphemeralBlockDeviceOutput) VirtualName() pulumi.StringOutput {
	return o.ApplyT(func (v AmiEphemeralBlockDevice) string { return v.VirtualName }).(pulumi.StringOutput)
}

type AmiEphemeralBlockDeviceArrayOutput struct { *pulumi.OutputState}

func (AmiEphemeralBlockDeviceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]AmiEphemeralBlockDevice)(nil)).Elem()
}

func (o AmiEphemeralBlockDeviceArrayOutput) ToAmiEphemeralBlockDeviceArrayOutput() AmiEphemeralBlockDeviceArrayOutput {
	return o
}

func (o AmiEphemeralBlockDeviceArrayOutput) ToAmiEphemeralBlockDeviceArrayOutputWithContext(ctx context.Context) AmiEphemeralBlockDeviceArrayOutput {
	return o
}

func (o AmiEphemeralBlockDeviceArrayOutput) Index(i pulumi.IntInput) AmiEphemeralBlockDeviceOutput {
	return pulumi.All(o, i).ApplyT(func (vs []interface{}) AmiEphemeralBlockDevice {
		return vs[0].([]AmiEphemeralBlockDevice)[vs[1].(int)]
	}).(AmiEphemeralBlockDeviceOutput)
}

func init() {
	pulumi.RegisterOutputType(AmiEphemeralBlockDeviceOutput{})
	pulumi.RegisterOutputType(AmiEphemeralBlockDeviceArrayOutput{})
}
