// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package getRouteTablesFilter

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type GetRouteTablesFilter struct {
	// The name of the field to filter by, as defined by
	// [the underlying AWS API](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeRouteTables.html).
	Name string `pulumi:"name"`
	// Set of values that are accepted for the given field.
	// A Route Table will be selected if any one of the given values matches.
	Values []string `pulumi:"values"`
}

type GetRouteTablesFilterInput interface {
	pulumi.Input

	ToGetRouteTablesFilterOutput() GetRouteTablesFilterOutput
	ToGetRouteTablesFilterOutputWithContext(context.Context) GetRouteTablesFilterOutput
}

type GetRouteTablesFilterArgs struct {
	// The name of the field to filter by, as defined by
	// [the underlying AWS API](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeRouteTables.html).
	Name pulumi.StringInput `pulumi:"name"`
	// Set of values that are accepted for the given field.
	// A Route Table will be selected if any one of the given values matches.
	Values pulumi.StringArrayInput `pulumi:"values"`
}

func (GetRouteTablesFilterArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetRouteTablesFilter)(nil)).Elem()
}

func (i GetRouteTablesFilterArgs) ToGetRouteTablesFilterOutput() GetRouteTablesFilterOutput {
	return i.ToGetRouteTablesFilterOutputWithContext(context.Background())
}

func (i GetRouteTablesFilterArgs) ToGetRouteTablesFilterOutputWithContext(ctx context.Context) GetRouteTablesFilterOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetRouteTablesFilterOutput)
}

type GetRouteTablesFilterArrayInput interface {
	pulumi.Input

	ToGetRouteTablesFilterArrayOutput() GetRouteTablesFilterArrayOutput
	ToGetRouteTablesFilterArrayOutputWithContext(context.Context) GetRouteTablesFilterArrayOutput
}

type GetRouteTablesFilterArray []GetRouteTablesFilterInput

func (GetRouteTablesFilterArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetRouteTablesFilter)(nil)).Elem()
}

func (i GetRouteTablesFilterArray) ToGetRouteTablesFilterArrayOutput() GetRouteTablesFilterArrayOutput {
	return i.ToGetRouteTablesFilterArrayOutputWithContext(context.Background())
}

func (i GetRouteTablesFilterArray) ToGetRouteTablesFilterArrayOutputWithContext(ctx context.Context) GetRouteTablesFilterArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetRouteTablesFilterArrayOutput)
}

type GetRouteTablesFilterOutput struct { *pulumi.OutputState }

func (GetRouteTablesFilterOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetRouteTablesFilter)(nil)).Elem()
}

func (o GetRouteTablesFilterOutput) ToGetRouteTablesFilterOutput() GetRouteTablesFilterOutput {
	return o
}

func (o GetRouteTablesFilterOutput) ToGetRouteTablesFilterOutputWithContext(ctx context.Context) GetRouteTablesFilterOutput {
	return o
}

// The name of the field to filter by, as defined by
// [the underlying AWS API](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeRouteTables.html).
func (o GetRouteTablesFilterOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func (v GetRouteTablesFilter) string { return v.Name }).(pulumi.StringOutput)
}

// Set of values that are accepted for the given field.
// A Route Table will be selected if any one of the given values matches.
func (o GetRouteTablesFilterOutput) Values() pulumi.StringArrayOutput {
	return o.ApplyT(func (v GetRouteTablesFilter) []string { return v.Values }).(pulumi.StringArrayOutput)
}

type GetRouteTablesFilterArrayOutput struct { *pulumi.OutputState}

func (GetRouteTablesFilterArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetRouteTablesFilter)(nil)).Elem()
}

func (o GetRouteTablesFilterArrayOutput) ToGetRouteTablesFilterArrayOutput() GetRouteTablesFilterArrayOutput {
	return o
}

func (o GetRouteTablesFilterArrayOutput) ToGetRouteTablesFilterArrayOutputWithContext(ctx context.Context) GetRouteTablesFilterArrayOutput {
	return o
}

func (o GetRouteTablesFilterArrayOutput) Index(i pulumi.IntInput) GetRouteTablesFilterOutput {
	return pulumi.All(o, i).ApplyT(func (vs []interface{}) GetRouteTablesFilter {
		return vs[0].([]GetRouteTablesFilter)[vs[1].(int)]
	}).(GetRouteTablesFilterOutput)
}

func init() {
	pulumi.RegisterOutputType(GetRouteTablesFilterOutput{})
	pulumi.RegisterOutputType(GetRouteTablesFilterArrayOutput{})
}
