// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package AnalyticsApplicationOutputKinesisStream

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type AnalyticsApplicationOutputKinesisStream struct {
	ResourceArn string `pulumi:"resourceArn"`
	RoleArn string `pulumi:"roleArn"`
}

type AnalyticsApplicationOutputKinesisStreamInput interface {
	pulumi.Input

	ToAnalyticsApplicationOutputKinesisStreamOutput() AnalyticsApplicationOutputKinesisStreamOutput
	ToAnalyticsApplicationOutputKinesisStreamOutputWithContext(context.Context) AnalyticsApplicationOutputKinesisStreamOutput
}

type AnalyticsApplicationOutputKinesisStreamArgs struct {
	ResourceArn pulumi.StringInput `pulumi:"resourceArn"`
	RoleArn pulumi.StringInput `pulumi:"roleArn"`
}

func (AnalyticsApplicationOutputKinesisStreamArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AnalyticsApplicationOutputKinesisStream)(nil)).Elem()
}

func (i AnalyticsApplicationOutputKinesisStreamArgs) ToAnalyticsApplicationOutputKinesisStreamOutput() AnalyticsApplicationOutputKinesisStreamOutput {
	return i.ToAnalyticsApplicationOutputKinesisStreamOutputWithContext(context.Background())
}

func (i AnalyticsApplicationOutputKinesisStreamArgs) ToAnalyticsApplicationOutputKinesisStreamOutputWithContext(ctx context.Context) AnalyticsApplicationOutputKinesisStreamOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AnalyticsApplicationOutputKinesisStreamOutput)
}

func (i AnalyticsApplicationOutputKinesisStreamArgs) ToAnalyticsApplicationOutputKinesisStreamPtrOutput() AnalyticsApplicationOutputKinesisStreamPtrOutput {
	return i.ToAnalyticsApplicationOutputKinesisStreamPtrOutputWithContext(context.Background())
}

func (i AnalyticsApplicationOutputKinesisStreamArgs) ToAnalyticsApplicationOutputKinesisStreamPtrOutputWithContext(ctx context.Context) AnalyticsApplicationOutputKinesisStreamPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AnalyticsApplicationOutputKinesisStreamOutput).ToAnalyticsApplicationOutputKinesisStreamPtrOutputWithContext(ctx)
}

type AnalyticsApplicationOutputKinesisStreamPtrInput interface {
	pulumi.Input

	ToAnalyticsApplicationOutputKinesisStreamPtrOutput() AnalyticsApplicationOutputKinesisStreamPtrOutput
	ToAnalyticsApplicationOutputKinesisStreamPtrOutputWithContext(context.Context) AnalyticsApplicationOutputKinesisStreamPtrOutput
}

type analyticsApplicationOutputKinesisStreamPtrType AnalyticsApplicationOutputKinesisStreamArgs

func AnalyticsApplicationOutputKinesisStreamPtr(v *AnalyticsApplicationOutputKinesisStreamArgs) AnalyticsApplicationOutputKinesisStreamPtrInput {	return (*analyticsApplicationOutputKinesisStreamPtrType)(v)
}

func (*analyticsApplicationOutputKinesisStreamPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**AnalyticsApplicationOutputKinesisStream)(nil)).Elem()
}

func (i *analyticsApplicationOutputKinesisStreamPtrType) ToAnalyticsApplicationOutputKinesisStreamPtrOutput() AnalyticsApplicationOutputKinesisStreamPtrOutput {
	return i.ToAnalyticsApplicationOutputKinesisStreamPtrOutputWithContext(context.Background())
}

func (i *analyticsApplicationOutputKinesisStreamPtrType) ToAnalyticsApplicationOutputKinesisStreamPtrOutputWithContext(ctx context.Context) AnalyticsApplicationOutputKinesisStreamPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AnalyticsApplicationOutputKinesisStreamPtrOutput)
}

type AnalyticsApplicationOutputKinesisStreamOutput struct { *pulumi.OutputState }

func (AnalyticsApplicationOutputKinesisStreamOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AnalyticsApplicationOutputKinesisStream)(nil)).Elem()
}

func (o AnalyticsApplicationOutputKinesisStreamOutput) ToAnalyticsApplicationOutputKinesisStreamOutput() AnalyticsApplicationOutputKinesisStreamOutput {
	return o
}

func (o AnalyticsApplicationOutputKinesisStreamOutput) ToAnalyticsApplicationOutputKinesisStreamOutputWithContext(ctx context.Context) AnalyticsApplicationOutputKinesisStreamOutput {
	return o
}

func (o AnalyticsApplicationOutputKinesisStreamOutput) ToAnalyticsApplicationOutputKinesisStreamPtrOutput() AnalyticsApplicationOutputKinesisStreamPtrOutput {
	return o.ToAnalyticsApplicationOutputKinesisStreamPtrOutputWithContext(context.Background())
}

func (o AnalyticsApplicationOutputKinesisStreamOutput) ToAnalyticsApplicationOutputKinesisStreamPtrOutputWithContext(ctx context.Context) AnalyticsApplicationOutputKinesisStreamPtrOutput {
	return o.ApplyT(func(v AnalyticsApplicationOutputKinesisStream) *AnalyticsApplicationOutputKinesisStream {
		return &v
	}).(AnalyticsApplicationOutputKinesisStreamPtrOutput)
}
func (o AnalyticsApplicationOutputKinesisStreamOutput) ResourceArn() pulumi.StringOutput {
	return o.ApplyT(func (v AnalyticsApplicationOutputKinesisStream) string { return v.ResourceArn }).(pulumi.StringOutput)
}

func (o AnalyticsApplicationOutputKinesisStreamOutput) RoleArn() pulumi.StringOutput {
	return o.ApplyT(func (v AnalyticsApplicationOutputKinesisStream) string { return v.RoleArn }).(pulumi.StringOutput)
}

type AnalyticsApplicationOutputKinesisStreamPtrOutput struct { *pulumi.OutputState}

func (AnalyticsApplicationOutputKinesisStreamPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AnalyticsApplicationOutputKinesisStream)(nil)).Elem()
}

func (o AnalyticsApplicationOutputKinesisStreamPtrOutput) ToAnalyticsApplicationOutputKinesisStreamPtrOutput() AnalyticsApplicationOutputKinesisStreamPtrOutput {
	return o
}

func (o AnalyticsApplicationOutputKinesisStreamPtrOutput) ToAnalyticsApplicationOutputKinesisStreamPtrOutputWithContext(ctx context.Context) AnalyticsApplicationOutputKinesisStreamPtrOutput {
	return o
}

func (o AnalyticsApplicationOutputKinesisStreamPtrOutput) Elem() AnalyticsApplicationOutputKinesisStreamOutput {
	return o.ApplyT(func (v *AnalyticsApplicationOutputKinesisStream) AnalyticsApplicationOutputKinesisStream { return *v }).(AnalyticsApplicationOutputKinesisStreamOutput)
}

func (o AnalyticsApplicationOutputKinesisStreamPtrOutput) ResourceArn() pulumi.StringOutput {
	return o.ApplyT(func (v AnalyticsApplicationOutputKinesisStream) string { return v.ResourceArn }).(pulumi.StringOutput)
}

func (o AnalyticsApplicationOutputKinesisStreamPtrOutput) RoleArn() pulumi.StringOutput {
	return o.ApplyT(func (v AnalyticsApplicationOutputKinesisStream) string { return v.RoleArn }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(AnalyticsApplicationOutputKinesisStreamOutput{})
	pulumi.RegisterOutputType(AnalyticsApplicationOutputKinesisStreamPtrOutput{})
}
