// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ec2

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupSubnet(ctx *pulumi.Context, args *LookupSubnetArgs, opts ...pulumi.InvokeOption) (*LookupSubnetResult, error) {
	var rv LookupSubnetResult
	err := ctx.Invoke("aws:ec2/getSubnet:getSubnet", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSubnet.
type LookupSubnetArgs struct {
	AvailabilityZone   *string           `pulumi:"availabilityZone"`
	AvailabilityZoneId *string           `pulumi:"availabilityZoneId"`
	CidrBlock          *string           `pulumi:"cidrBlock"`
	DefaultForAz       *bool             `pulumi:"defaultForAz"`
	Filters            []GetSubnetFilter `pulumi:"filters"`
	Id                 *string           `pulumi:"id"`
	Ipv6CidrBlock      *string           `pulumi:"ipv6CidrBlock"`
	State              *string           `pulumi:"state"`
	Tags               map[string]string `pulumi:"tags"`
	VpcId              *string           `pulumi:"vpcId"`
}

// A collection of values returned by getSubnet.
type LookupSubnetResult struct {
	Arn                         string            `pulumi:"arn"`
	AssignIpv6AddressOnCreation bool              `pulumi:"assignIpv6AddressOnCreation"`
	AvailabilityZone            string            `pulumi:"availabilityZone"`
	AvailabilityZoneId          string            `pulumi:"availabilityZoneId"`
	CidrBlock                   string            `pulumi:"cidrBlock"`
	DefaultForAz                bool              `pulumi:"defaultForAz"`
	Filters                     []GetSubnetFilter `pulumi:"filters"`
	Id                          string            `pulumi:"id"`
	Ipv6CidrBlock               string            `pulumi:"ipv6CidrBlock"`
	Ipv6CidrBlockAssociationId  string            `pulumi:"ipv6CidrBlockAssociationId"`
	MapPublicIpOnLaunch         bool              `pulumi:"mapPublicIpOnLaunch"`
	OutpostArn                  string            `pulumi:"outpostArn"`
	OwnerId                     string            `pulumi:"ownerId"`
	State                       string            `pulumi:"state"`
	Tags                        map[string]string `pulumi:"tags"`
	VpcId                       string            `pulumi:"vpcId"`
}
