// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package storagegateway

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type SmbFileShare struct {
	pulumi.CustomResourceState

	Arn                  pulumi.StringOutput      `pulumi:"arn"`
	Authentication       pulumi.StringPtrOutput   `pulumi:"authentication"`
	DefaultStorageClass  pulumi.StringPtrOutput   `pulumi:"defaultStorageClass"`
	FileshareId          pulumi.StringOutput      `pulumi:"fileshareId"`
	GatewayArn           pulumi.StringOutput      `pulumi:"gatewayArn"`
	GuessMimeTypeEnabled pulumi.BoolPtrOutput     `pulumi:"guessMimeTypeEnabled"`
	InvalidUserLists     pulumi.StringArrayOutput `pulumi:"invalidUserLists"`
	KmsEncrypted         pulumi.BoolPtrOutput     `pulumi:"kmsEncrypted"`
	KmsKeyArn            pulumi.StringPtrOutput   `pulumi:"kmsKeyArn"`
	LocationArn          pulumi.StringOutput      `pulumi:"locationArn"`
	ObjectAcl            pulumi.StringPtrOutput   `pulumi:"objectAcl"`
	Path                 pulumi.StringOutput      `pulumi:"path"`
	ReadOnly             pulumi.BoolPtrOutput     `pulumi:"readOnly"`
	RequesterPays        pulumi.BoolPtrOutput     `pulumi:"requesterPays"`
	RoleArn              pulumi.StringOutput      `pulumi:"roleArn"`
	Tags                 pulumi.StringMapOutput   `pulumi:"tags"`
	ValidUserLists       pulumi.StringArrayOutput `pulumi:"validUserLists"`
}

// NewSmbFileShare registers a new resource with the given unique name, arguments, and options.
func NewSmbFileShare(ctx *pulumi.Context,
	name string, args *SmbFileShareArgs, opts ...pulumi.ResourceOption) (*SmbFileShare, error) {
	if args == nil || args.GatewayArn == nil {
		return nil, errors.New("missing required argument 'GatewayArn'")
	}
	if args == nil || args.LocationArn == nil {
		return nil, errors.New("missing required argument 'LocationArn'")
	}
	if args == nil || args.RoleArn == nil {
		return nil, errors.New("missing required argument 'RoleArn'")
	}
	if args == nil {
		args = &SmbFileShareArgs{}
	}
	var resource SmbFileShare
	err := ctx.RegisterResource("aws:storagegateway/smbFileShare:SmbFileShare", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSmbFileShare gets an existing SmbFileShare resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSmbFileShare(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SmbFileShareState, opts ...pulumi.ResourceOption) (*SmbFileShare, error) {
	var resource SmbFileShare
	err := ctx.ReadResource("aws:storagegateway/smbFileShare:SmbFileShare", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SmbFileShare resources.
type smbFileShareState struct {
	Arn                  *string           `pulumi:"arn"`
	Authentication       *string           `pulumi:"authentication"`
	DefaultStorageClass  *string           `pulumi:"defaultStorageClass"`
	FileshareId          *string           `pulumi:"fileshareId"`
	GatewayArn           *string           `pulumi:"gatewayArn"`
	GuessMimeTypeEnabled *bool             `pulumi:"guessMimeTypeEnabled"`
	InvalidUserLists     []string          `pulumi:"invalidUserLists"`
	KmsEncrypted         *bool             `pulumi:"kmsEncrypted"`
	KmsKeyArn            *string           `pulumi:"kmsKeyArn"`
	LocationArn          *string           `pulumi:"locationArn"`
	ObjectAcl            *string           `pulumi:"objectAcl"`
	Path                 *string           `pulumi:"path"`
	ReadOnly             *bool             `pulumi:"readOnly"`
	RequesterPays        *bool             `pulumi:"requesterPays"`
	RoleArn              *string           `pulumi:"roleArn"`
	Tags                 map[string]string `pulumi:"tags"`
	ValidUserLists       []string          `pulumi:"validUserLists"`
}

type SmbFileShareState struct {
	Arn                  pulumi.StringPtrInput
	Authentication       pulumi.StringPtrInput
	DefaultStorageClass  pulumi.StringPtrInput
	FileshareId          pulumi.StringPtrInput
	GatewayArn           pulumi.StringPtrInput
	GuessMimeTypeEnabled pulumi.BoolPtrInput
	InvalidUserLists     pulumi.StringArrayInput
	KmsEncrypted         pulumi.BoolPtrInput
	KmsKeyArn            pulumi.StringPtrInput
	LocationArn          pulumi.StringPtrInput
	ObjectAcl            pulumi.StringPtrInput
	Path                 pulumi.StringPtrInput
	ReadOnly             pulumi.BoolPtrInput
	RequesterPays        pulumi.BoolPtrInput
	RoleArn              pulumi.StringPtrInput
	Tags                 pulumi.StringMapInput
	ValidUserLists       pulumi.StringArrayInput
}

func (SmbFileShareState) ElementType() reflect.Type {
	return reflect.TypeOf((*smbFileShareState)(nil)).Elem()
}

type smbFileShareArgs struct {
	Authentication       *string           `pulumi:"authentication"`
	DefaultStorageClass  *string           `pulumi:"defaultStorageClass"`
	GatewayArn           string            `pulumi:"gatewayArn"`
	GuessMimeTypeEnabled *bool             `pulumi:"guessMimeTypeEnabled"`
	InvalidUserLists     []string          `pulumi:"invalidUserLists"`
	KmsEncrypted         *bool             `pulumi:"kmsEncrypted"`
	KmsKeyArn            *string           `pulumi:"kmsKeyArn"`
	LocationArn          string            `pulumi:"locationArn"`
	ObjectAcl            *string           `pulumi:"objectAcl"`
	ReadOnly             *bool             `pulumi:"readOnly"`
	RequesterPays        *bool             `pulumi:"requesterPays"`
	RoleArn              string            `pulumi:"roleArn"`
	Tags                 map[string]string `pulumi:"tags"`
	ValidUserLists       []string          `pulumi:"validUserLists"`
}

// The set of arguments for constructing a SmbFileShare resource.
type SmbFileShareArgs struct {
	Authentication       pulumi.StringPtrInput
	DefaultStorageClass  pulumi.StringPtrInput
	GatewayArn           pulumi.StringInput
	GuessMimeTypeEnabled pulumi.BoolPtrInput
	InvalidUserLists     pulumi.StringArrayInput
	KmsEncrypted         pulumi.BoolPtrInput
	KmsKeyArn            pulumi.StringPtrInput
	LocationArn          pulumi.StringInput
	ObjectAcl            pulumi.StringPtrInput
	ReadOnly             pulumi.BoolPtrInput
	RequesterPays        pulumi.BoolPtrInput
	RoleArn              pulumi.StringInput
	Tags                 pulumi.StringMapInput
	ValidUserLists       pulumi.StringArrayInput
}

func (SmbFileShareArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*smbFileShareArgs)(nil)).Elem()
}
