// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export class Selection extends pulumi.CustomResource {
    /**
     * Get an existing Selection resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SelectionState, opts?: pulumi.CustomResourceOptions): Selection {
        return new Selection(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'aws:backup/selection:Selection';

    /**
     * Returns true if the given object is an instance of Selection.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Selection {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Selection.__pulumiType;
    }

    public readonly iamRoleArn!: pulumi.Output<string>;
    public readonly name!: pulumi.Output<string>;
    public readonly planId!: pulumi.Output<string>;
    public readonly resources!: pulumi.Output<string[] | undefined>;
    public readonly selectionTags!: pulumi.Output<outputs.backup.SelectionSelectionTag[] | undefined>;

    /**
     * Create a Selection resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SelectionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SelectionArgs | SelectionState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as SelectionState | undefined;
            inputs["iamRoleArn"] = state ? state.iamRoleArn : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["planId"] = state ? state.planId : undefined;
            inputs["resources"] = state ? state.resources : undefined;
            inputs["selectionTags"] = state ? state.selectionTags : undefined;
        } else {
            const args = argsOrState as SelectionArgs | undefined;
            if (!args || args.iamRoleArn === undefined) {
                throw new Error("Missing required property 'iamRoleArn'");
            }
            if (!args || args.planId === undefined) {
                throw new Error("Missing required property 'planId'");
            }
            inputs["iamRoleArn"] = args ? args.iamRoleArn : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["planId"] = args ? args.planId : undefined;
            inputs["resources"] = args ? args.resources : undefined;
            inputs["selectionTags"] = args ? args.selectionTags : undefined;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(Selection.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Selection resources.
 */
export interface SelectionState {
    readonly iamRoleArn?: pulumi.Input<string>;
    readonly name?: pulumi.Input<string>;
    readonly planId?: pulumi.Input<string>;
    readonly resources?: pulumi.Input<pulumi.Input<string>[]>;
    readonly selectionTags?: pulumi.Input<pulumi.Input<inputs.backup.SelectionSelectionTag>[]>;
}

/**
 * The set of arguments for constructing a Selection resource.
 */
export interface SelectionArgs {
    readonly iamRoleArn: pulumi.Input<string>;
    readonly name?: pulumi.Input<string>;
    readonly planId: pulumi.Input<string>;
    readonly resources?: pulumi.Input<pulumi.Input<string>[]>;
    readonly selectionTags?: pulumi.Input<pulumi.Input<inputs.backup.SelectionSelectionTag>[]>;
}
