// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package iot

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func GetEndpoint(ctx *pulumi.Context, args *GetEndpointArgs, opts ...pulumi.InvokeOption) (*GetEndpointResult, error) {
	var rv GetEndpointResult
	err := ctx.Invoke("aws:iot/getEndpoint:getEndpoint", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getEndpoint.
type GetEndpointArgs struct {
	EndpointType *string `pulumi:"endpointType"`
}

// A collection of values returned by getEndpoint.
type GetEndpointResult struct {
	EndpointAddress string  `pulumi:"endpointAddress"`
	EndpointType    *string `pulumi:"endpointType"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
}
